name: 'Push Dockerised Application to ECR'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

# Required to use Github OIDC Token with AWS
permissions:
  id-token: write

env:
  AWS_REGION: eu-west-1

jobs:
  run-automated-tests:
    name: 'Run Automated Tests'
    environment: ${{ env.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Automated Tests
        run: ./mvnw verify

  push-to-ecr:
    name: 'Push Dockerised Application to ECR'
    needs: run-automated-tests
    environment: ${{ env.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets[format('{0}_AWS_ACCOUNT_ID', inputs.environment)] }}:role/RoleForGithubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create Image Tag
        id: create-image-tag
        run: |
          IMAGE_TAG=$(date +%Y%m%d-%H%M)-${GITHUB_SHA::7}
          echo "::notice title=Using Artifact Image Tag::$IMAGE_TAG"
          echo "::set-output name=image_tag::$IMAGE_TAG"

      - name: Build, Tag and Push Image to AWS ECR
        env:
          IMAGE_TAG: ${{ steps.create-image-tag.outputs.image_tag }}
        run: |
          set -o pipefail
          ECR_REPO_URL=$(aws ssm get-parameter --name /ecr/deployment-artifacts/smalldomains/domain-manager --with-decryption | jq -r '.Parameter.Value')
          docker build -t $ECR_REPO_URL:$IMAGE_TAG .
          docker push $ECR_REPO_URL:$IMAGE_TAG