name: 'Push Dockerised Application to ECR'

on:
  push: #TODO remove
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

# TODO update environment

# Required to use Github OIDC Token with AWS
permissions:
  id-token: write

env:
  AWS_REGION: eu-west-1

jobs:
  retrieve-ssm-params:
    name: 'Retrieve Required SSM Params'
    environment: development
    runs-on: ubuntu-latest

    outputs:
      ecr_repo_url: ${{ steps.ecr_repo_url.outputs.ecr_repo_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::646359775865:role/RoleForGithubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Retrieve ECR Repository URL
        id: ecr_repo_url
        # I'm using this weird double-encoding because Github thinks that ECR_REPO_URL is a secret and doesn't let us set it as output
        # So, I'm using this hacky workaround... but Github should really let us correct its auto-secret-detection
        # https://github.community/t/environment-url-not-set-because-env-may-contain-secret/153708/23
        run: |
          echo "::set-output name=ecr_repo_url::$(aws ssm get-parameter --name /ecr/deployment-artifacts/smalldomains/domain-manager --with-decryption | jq -r '.Parameter.Value')"

  run-automated-tests:
    name: 'Run Automated Tests'
    environment: development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Automated Tests
        run: ./mvnw verify

  push-to-ecr:
    name: 'Push Dockerised Application to ECR'
    needs:
      - run-automated-tests
      - retrieve-ssm-params
    environment: development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # TODO dont use hardcoded account id
          role-to-assume: arn:aws:iam::646359775865:role/RoleForGithubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create Image Tag
        id: create-image-tag
        run: |
          IMAGE_TAG=$(date +%Y%m%d-%H%M)-${GITHUB_SHA::7}
          echo "::notice title=Using Artifact Image Tag::$IMAGE_TAG"
          echo "::set-output name=image_tag::$IMAGE_TAG"

      - name: Build, Tag and Push Image to AWS ECR
        env:
          ECR_REPO_URL: ${{ needs.retrieve-ssm-params.outputs.ecr_repo_url }}
          IMAGE_TAG: ${{ steps.create-image-tag.outputs.image_tag }}
        run: |
          docker build -t $ECR_REPO_URL:$IMAGE_TAG .
          docker push $ECR_REPO_URL:$IMAGE_TAG