name: 'Deploy to Development'

on:
  push:

# Required to use Github OIDC Token with AWS
permissions:
  id-token: write

jobs:
  run-automated-tests:
    name: 'Run Automated Tests'
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Automated Tests
        run: ./mvnw verify

  push-docker-image:
    name: 'Push Docker Image to ECR'
    needs: run-automated-tests
    uses: ./.github/workflows/application--deploy_image_specified_env.yml
    with:
      environment: development

  deploy-infrastructure:
    name: 'Deploy DEV Infrastructure'
    needs: push-docker-image
    uses: ./.github/workflows/infrastructure--deploy_specified_env.yml
    with:
      environment: development
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}