name: 'Promote Deployment to Higher Environments'

on:
  push:
    branches:
      - main

jobs:
  is-terraform-code-formatted:
    name: 'Check Code Format'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check

  push-docker-image:
    name: 'Push Docker Image to ECR'
    needs: is-terraform-code-formatted
    environment: production
    runs-on: ubuntu-latest

    uses: ./.github/workflows/push_image.yml
    with:
      environment: production

  deploy-prod-application:
    name: 'Deploy Application to PROD'
    needs: push-docker-image
    environment: production
    runs-on: ubuntu-latest

    uses: ./.github/workflows/deploy_infrastructure.yml
    with:
      environment: production
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}