name: 'Deploy to Development'

on:
  push:

jobs:
  deploy-infrastructure:
    name: 'Deploy DEV Infrastructure'
    uses: ./.github/workflows/infrastructure--deploy_specified_env.yml
    with:
      environment: development
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}