name: 'Promote Deployment to higher environments'

on:
  push:
    branches:
      - main
      - feature/terraform_provisioning

jobs:
  is-terraform-code-formatted:
    name: 'Check Code Format'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check

  deploy-stage-infrastructure:
    name: 'Deploy STAGE Infrastructure'
    needs: is-terraform-code-formatted
    uses: ./.github/workflows/infrastructure--deploy_specified_env.yml
    with:
      environment: staging
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  deploy-stage-application:
    name: 'Deploy Application to STAGE'
    needs: deploy-stage-infrastructure
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: Placeholder Step
        run: echo "Deploy Application to Stage"

  require-approval-for-prod-deployment:
    name: 'Validate Staging: Authorise PROD Deployment'
    needs: deploy-stage-application
    environment: manual-approval-for-prod
    runs-on: ubuntu-latest

  destroy-stage-application:
    name: 'Destroy Application on STAGE'
    needs: require-approval-for-prod-deployment
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: Placeholder Step
        run: echo "Destroy Application on Stage"

  destroy-stage-infrastructure:
    name: 'Destroy STAGE Infrastructure'
    needs: destroy-stage-application
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: Placeholder Step
        run: echo "Destroy Infrastructure on Stage"

  deploy-prod-infrastructure:
    name: 'Deploy PROD Infrastructure'
    needs: require-approval-for-prod-deployment
    uses: ./.github/workflows/infrastructure--deploy_specified_env.yml
    with:
      environment: production
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  deploy-prod-application:
    name: 'Deploy Application to PROD'
    needs: deploy-prod-infrastructure
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Placeholder Step
        run: echo "Destroy Infrastructure on Stage"