name: 'Deploy to Development'

on:
  push:

# Required to use Github OIDC Token with AWS
permissions:
  id-token: write


jobs:
  push-docker-image:
    name: 'Push Docker Image to ECR'
    uses: ./.github/workflows/application--deploy_image_specified_env.yml
    with:
      environment: development

  deploy-infrastructure:
    name: 'Deploy DEV Infrastructure'
    uses: ./.github/workflows/infrastructure--deploy_specified_env.yml
    with:
      environment: development
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}