name: 'Destroy Staging Infrastructure'

on:
  workflow_call:

jobs:
  destroy-staging-infrastructure:
    name: 'Destroy Staging Infrastructure'
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: smalldomains--domain-manager-stage

    defaults:
      run:
        shell: bash

    steps:
      - name: Begin Destruction of Stage Infrastructure
        run: echo "Destroying infrastructure on staging environment"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve
